/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen;

import javax.swing.JOptionPane;



/**
 *
 * @author ESFOT
 */
public class Calculador extends javax.swing.JFrame {
    boolean triangulo= false;  
    /**
     * Creates new form Calculador
     */
    public Calculador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnCalcu = new javax.swing.JButton();
        cbxTriangulos = new javax.swing.JComboBox<>();
        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        txtAng = new javax.swing.JTextField();
        lblC = new javax.swing.JLabel();
        txtC = new javax.swing.JTextField();
        lblAr = new javax.swing.JLabel();
        lblPer = new javax.swing.JLabel();
        lblAlt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TRIANGULOS");

        jLabel2.setText("Tipo de triangulo");

        lblA.setText("Lado a");

        lblB.setText("Lado b");

        jLabel5.setText("Ángulo formado entre los lados");

        jLabel6.setText("RESULTADOS");

        jLabel7.setText("Area:");

        jLabel8.setText("Perimetro:");

        jLabel9.setText("Altura:");

        btnCalcu.setText("Calcular");
        btnCalcu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcuActionPerformed(evt);
            }
        });

        cbxTriangulos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rectángulo", "Isósceles", "Escaleno", "Equilátero" }));
        cbxTriangulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTriangulosActionPerformed(evt);
            }
        });

        lblC.setText("Lado c");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblA)
                            .addComponent(lblB))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtA, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                .addComponent(txtB))
                            .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(329, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxTriangulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(lblAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(lblAr, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(lblPer, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblC))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnCalcu))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAng, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(cbxTriangulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAr, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblA)
                    .addComponent(jLabel8)
                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPer, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblB)
                    .addComponent(jLabel9)
                    .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblC)
                    .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalcu)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxTriangulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTriangulosActionPerformed
        // TODO add your handling code here:
        if(cbxTriangulos.getSelectedItem().toString().equals("Rectángulo")){
        lblA.setVisible(true);
        txtA.setVisible(true);
        lblB.setVisible(true);
        txtB.setVisible(true);
        lblC.setVisible(false);
        txtC.setVisible(false);
        txtAng.setText("90"); 
        
        } else if(cbxTriangulos.getSelectedItem().toString().equals("Isósceles")){
                lblA.setVisible(true);
                txtA.setVisible(true);
                lblB.setVisible(true);
                txtB.setVisible(true);    
                lblC.setVisible(false);
                txtC.setVisible(false);
                txtAng.setText(null);
                }else if (cbxTriangulos.getSelectedItem().toString().equals("Escaleno")){
                lblA.setVisible(true);
                txtA.setVisible(true);
                lblB.setVisible(true);
                txtB.setVisible(true);    
                lblC.setVisible(true);
                txtC.setVisible(true);
                txtAng.setText(null);
                }else if (cbxTriangulos.getSelectedItem().toString().equals("Equilátero")){
                 lblA.setVisible(true);
                txtA.setVisible(true);
                lblB.setVisible(false);
                txtB.setVisible(false);    
                lblC.setVisible(false);
                txtC.setVisible(false); 
                txtAng.setText(null);
                }
    }//GEN-LAST:event_cbxTriangulosActionPerformed

    private void btnCalcuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcuActionPerformed
        // TODO add your handling code here:
         if(cbxTriangulos.getSelectedItem().toString().equals("Rectángulo")){
             double a = Double.parseDouble(txtA.getText());
             double b = Double.parseDouble(txtB.getText());
             double aC = Math.pow(a, 2.0);
             double bC = Math.pow(b , 2.0); 
             double c = Math.sqrt(aC + bC); 
             verif(a,b,c); 
             if(triangulo==false){
                 txtA.setText(null);
                 txtB.setText(null);
                 txtC.setText(null);
                 JOptionPane.showMessageDialog(rootPane, "No es un triangulo!", "Ingrese datos validos!", HEIGHT);
             }else if (triangulo == true){
                 TrRectangulo t = new TrRectangulo(a,b,c); 
                 String area= String.valueOf(t.CalcularArea());
                 String p= String.valueOf(t.CalcularPerimetro());
                 String h= String.valueOf(t.CalcularAltura());
                 lblAr.setText(area);
                 lblPer.setText(p);
                 lblAlt.setText(h);
              
             } 
                 
             }else if (cbxTriangulos.getSelectedItem().toString().equals("Isósceles")){
                 double a = Double.parseDouble(txtA.getText());
                 double b = Double.parseDouble(txtB.getText());
                 double c = a; 
                 verif(a,b,c);
                   if(triangulo==false){
                 txtA.setText(null);
                 txtB.setText(null);
                 JOptionPane.showMessageDialog(rootPane, "No es un triangulo!", "Ingrese datos validos!", HEIGHT);
             }else if (triangulo == true){
                 TrIsosceles t = new TrIsosceles(a,b,c); 
                 String area= String.valueOf(t.CalcularArea());
                 String p= String.valueOf(t.CalcularPerimetro());
                 String h= String.valueOf(t.CalcularAltura());
                 lblAr.setText(area);
                 lblPer.setText(p);
                 lblAlt.setText(h);
             }
            
             
         } else if (cbxTriangulos.getSelectedItem().toString().equals("Equilátero")){
              double a = Double.parseDouble(txtA.getText());
              double b= a;
              double c= a;
              verif(a,b,c);
               if(triangulo==false){
                 txtA.setText(null);
                 txtB.setText(null);
                 JOptionPane.showMessageDialog(rootPane, "No es un triangulo!", "Ingrese datos validos!", HEIGHT);
               }else if (triangulo == true){
                 TrEquilatero t = new TrEquilatero(a,b,c); 
                 String area= String.valueOf(t.CalcularArea());
                 String p= String.valueOf(t.CalcularPerimetro());
                 String h= String.valueOf(t.CalcularAltura());
                 lblAr.setText(area);
                 lblPer.setText(p);
                 lblAlt.setText(h);
             
         }
    }//GEN-LAST:event_btnCalcuActionPerformed
         else if (cbxTriangulos.getSelectedItem().toString().equals("Escaleno")){
                 
                 if(!(txtA.getText().equals(txtB.getText()) || txtA.getText().equals(txtC.getText()) || txtB.getText().equals(txtC.getText()))){
                 double a = Double.parseDouble(txtA.getText());
                 double b = Double.parseDouble(txtB.getText());
                 double c = Double.parseDouble(txtC.getText()); 
                  verif(a,b,c);
               if(triangulo==false){
                 txtA.setText(null);
                 txtB.setText(null);
                 txtC.setText(null); 
                 JOptionPane.showMessageDialog(rootPane, "No es un triangulo!", "Ingrese datos validos!", HEIGHT);
                  }else if (triangulo == true){
                 TrEscaleno t = new TrEscaleno(a,b,c); 
                 String area= String.valueOf(t.CalcularArea());
                 String p= String.valueOf(t.CalcularPerimetro());
                 String h= String.valueOf(t.CalcularAltura());
                 lblAr.setText(area);
                 lblPer.setText(p);
                 lblAlt.setText(h);
                  
                 }
         }else{
       
                  JOptionPane.showMessageDialog(rootPane, "Ingrese lados diferentes entre si!", "No es un triangulo escaleno!", HEIGHT);
                 }
    }
    }
    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculador().setVisible(true);
            }
        });
    }
    
    public void verif (double a, double b, double c){
    if(a+b>c && b+c>a && a+c>b){
    triangulo=true; 
    }else{
     triangulo = false;  
    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcu;
    private javax.swing.JComboBox<String> cbxTriangulos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblAlt;
    private javax.swing.JLabel lblAr;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblPer;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtAng;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtC;
    // End of variables declaration//GEN-END:variables
}
